# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(936, 825)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(936, 825))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.states_spinB = QtWidgets.QSpinBox(self.centralwidget)
        self.states_spinB.setGeometry(QtCore.QRect(600, 120, 111, 31))
        self.states_spinB.setMinimum(1)
        self.states_spinB.setProperty("value", 2)
        self.states_spinB.setObjectName("states_spinB")
        self.strategys_spinB = QtWidgets.QSpinBox(self.centralwidget)
        self.strategys_spinB.setGeometry(QtCore.QRect(600, 50, 111, 31))
        self.strategys_spinB.setMinimum(1)
        self.strategys_spinB.setObjectName("strategys_spinB")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(600, 20, 121, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(600, 90, 121, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(600, 160, 121, 31))
        self.label_3.setObjectName("label_3")
        self.stages_spinB = QtWidgets.QSpinBox(self.centralwidget)
        self.stages_spinB.setGeometry(QtCore.QRect(600, 190, 111, 31))
        self.stages_spinB.setMinimum(1)
        self.stages_spinB.setObjectName("stages_spinB")
        self.matrices_tw = QtWidgets.QTabWidget(self.centralwidget)
        self.matrices_tw.setGeometry(QtCore.QRect(10, 10, 521, 331))
        self.matrices_tw.setObjectName("matrices_tw")
        self.probability_matrix = QtWidgets.QWidget()
        self.probability_matrix.setObjectName("probability_matrix")
        self.probabilitys_table = QtWidgets.QTableView(self.probability_matrix)
        self.probabilitys_table.setGeometry(QtCore.QRect(0, 0, 521, 301))
        self.probabilitys_table.setObjectName("probabilitys_table")
        self.probabilitys_table.horizontalHeader().setSortIndicatorShown(True)
        self.probabilitys_table.horizontalHeader().setStretchLastSection(True)
        self.probabilitys_table.verticalHeader().setStretchLastSection(True)
        self.matrices_tw.addTab(self.probability_matrix, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.yield_table = QtWidgets.QTableView(self.tab_2)
        self.yield_table.setGeometry(QtCore.QRect(-5, 0, 521, 301))
        self.yield_table.setFrameShadow(QtWidgets.QFrame.Plain)
        self.yield_table.setObjectName("yield_table")
        self.yield_table.horizontalHeader().setStretchLastSection(True)
        self.yield_table.verticalHeader().setStretchLastSection(True)
        self.matrices_tw.addTab(self.tab_2, "")
        self.changeNumbers_bt = QtWidgets.QPushButton(self.centralwidget)
        self.changeNumbers_bt.setGeometry(QtCore.QRect(750, 190, 93, 28))
        self.changeNumbers_bt.setObjectName("changeNumbers_bt")
        self.calcBt = QtWidgets.QPushButton(self.centralwidget)
        self.calcBt.setGeometry(QtCore.QRect(600, 280, 121, 31))
        self.calcBt.setObjectName("calcBt")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-3, 340, 941, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 360, 511, 411))
        self.textEdit.setObjectName("textEdit")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(524, 360, 411, 411))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(0, 0, 401, 391))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        # self.widget.setPalette(palette)
        # self.widget.setAutoFillBackground(True)
        # self.widget.setObjectName("widget")
        # self.tabWidget.addTab(self.tab, "")
        #
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 936, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.matrices_tw.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Число стратегий"))
        self.label_2.setText(_translate("MainWindow", "Число состояний"))
        self.label_3.setText(_translate("MainWindow", "Число этапов"))
        self.matrices_tw.setTabText(self.matrices_tw.indexOf(self.probability_matrix), _translate("MainWindow", "Матрица вероятностей"))
        self.matrices_tw.setTabText(self.matrices_tw.indexOf(self.tab_2), _translate("MainWindow", "Матрица доходностей"))
        self.changeNumbers_bt.setText(_translate("MainWindow", "Изменить"))
        self.calcBt.setText(_translate("MainWindow", "Вычислить"))
        # self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        # self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Tab 2"))
